### ISSUE TITLE
Firestoreの設計

### ISSUE THREAD

**Issue by daikimkw** [dlopp/question-box#10]
## 📌 Description
データベースにつかうやつ

**Comment by yuto14prog** [comment]
## CloudFirestoreに何を保存するかのメモ
- 質問文
  - post日時 
- 回答文
  - post日時
- 回答されているか否か（true or false）

## 階層
- Usersコレクション
  - UserID付きドキュメント
    - 質問コレクション
      - 質問ID付きドキュメント

多分こんな感じ

**Comment by daikimkw** [comment]
Usersコレクションいるかな
昨日使い方を見始めたからあんまりよくわかってないんやけど

**Comment by daikimkw** [comment]
@yuto14prog 
questionsコレクションに、質問内容、回答してるか、日時
answersコレクションに、回答内容、日時、questionのid

とかで良いかな
questionsコレクションはこんな感じ
![image](https://user-images.githubusercontent.com/67625825/111066278-7dfb1300-8501-11eb-9213-f0e000e418e7.png)

**Comment by yuto14prog** [comment]
questionとanswer分けるん？
questionコレクションのドキュメントのフィールドにanswer書いたら、idと紐付ける処理簡単になると思う

**Comment by daikimkw** [comment]
回答にも一意なid必要な気がする

作ってみないとわからんなーこの辺は

**Comment by daikimkw** [comment]
回答詳細と質問詳細ページ必要で両方にidはいるから例えば
/questions/質問id
で、回答を書くページにアクセスできて
/answers/回答id
で、Twitterにリンクするページにアクセスできるみたいな

回答id自体はあって困らん気はするんよな🤔

**Comment by yuto14prog** [comment]
たしかにあっても困らんな。
そんな複雑な処理する訳でもないと思うからanswerコレクションあっても良きなんかﾌﾑﾌﾑ

**Comment by daikimkw** [comment]
close
何かあれば別issue立てる
