### ISSUE TITLE
画面をデザインする

### ISSUE THREAD

**Issue by daikimkw** [dlopp/question-box#2]
## 📌 Description
画面を良い感じにする

## 🤔 Concern
フォームといままできた質問とその回答内容全部同じページにやってもいい気がする。  
回答内容を見るために一回ページまたぐのがめんどそうと思って  

## 💬 Discuss
- どんな雰囲気にするか
- デザインツールの選定

**Comment by daikimkw** [comment]
デザインツールはさかねさんが1番得意なやつで良いと思う〜
僕はXDなら手伝えます

**Comment by yuto14prog** [comment]
Twitter盛んな人は質問だらけになりそうやから、全部同じページにしたらめっちゃ長くなるね
せめて回答済みと未回答はタブかなんかで分けたほうが良きかも

**Comment by daikimkw** [comment]
お、一旦dloppだけ使うみたいなのを作るのかと思ってた（笑）
認証系をfirebaseでやればいけそうな気がするから一旦本家寄りで作ってみて無理そうやったら専用にシフトチェンジしても良さそう
個人的にはとにかく一画面にたくさん質問と回答を表示させたい感があるなあ少なくともpc画面では
回答済みしか表示されへんと思ってた、使う側のユーザーの話ならそれはそうね！

**Comment by yuto14prog** [comment]
なるほど一旦dloppだけか笑
最初はそのほうがよさそうな感じやね。

**Comment by daikimkw** [comment]
お、どうするどうする専用作る？

**Comment by yuto14prog** [comment]
専用でも公開でもやること変わらんような気がしてきた
> 一旦本家寄りで作ってみて無理そうやったら専用にシフトチェンジしても良さそう
>
これでいいのでは

**Comment by daikimkw** [comment]
まるパクリサービスを作って良いものかという気がしてきた（笑）
何かしらのオリジナリティは必要そうやけど後から考えればいっかそれは

**Comment by daikimkw** [comment]
> 専用でも公開でもやること変わらんような気がしてきた  

専用やとユーザー認証とかユーザー情報の保持あたりが楽になるんじゃないかな  
詳しくは分からんが

**Comment by ma-ma-hima** [comment]
専用にしたらいいと思う！

**Comment by yuto14prog** [comment]
2021/3/8 の会議にて専用の意味が解決ｗ！
専用でいいと思う

**Comment by daikimkw** [comment]
必要なページ
- top page 
  - フォームがトップにあってその下に過去の回答があるようなページ
- 質問の詳細ページ
  - twitterで共有するときにリンクするページ
- dlopp用の、届いた質問一覧
- 質問に回答するページ

**Comment by daikimkw** [comment]
404ページも必要
